// Mocks generated by Mockito 5.4.6 from annotations
// in hololine_server/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hololine_server/src/generated/protocol.dart' as _i2;
import 'package:hololine_server/src/repositories/workspace_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:serverpod/serverpod.dart' as _i3;
import 'package:serverpod/src/cache/caches.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkspace_0 extends _i1.SmartFake implements _i2.Workspace {
  _FakeWorkspace_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkspaceInvitation_1 extends _i1.SmartFake
    implements _i2.WorkspaceInvitation {
  _FakeWorkspaceInvitation_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkspaceMember_2 extends _i1.SmartFake
    implements _i2.WorkspaceMember {
  _FakeWorkspaceMember_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuidValue_3 extends _i1.SmartFake implements _i3.UuidValue {
  _FakeUuidValue_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServer_4 extends _i1.SmartFake implements _i3.Server {
  _FakeServer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerpod_5 extends _i1.SmartFake implements _i3.Serverpod {
  _FakeServerpod_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_6 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_7 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCaches_8 extends _i1.SmartFake implements _i4.Caches {
  _FakeCaches_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageAccess_9 extends _i1.SmartFake implements _i3.StorageAccess {
  _FakeStorageAccess_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageCentralAccess_10 extends _i1.SmartFake
    implements _i3.MessageCentralAccess {
  _FakeMessageCentralAccess_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_11 extends _i1.SmartFake implements Duration {
  _FakeDuration_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepo extends _i1.Mock implements _i5.WorkspaceRepo {
  MockWorkspaceRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Workspace?> findByNameAndOwner(
    _i3.Session? session,
    String? name,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByNameAndOwner,
          [
            session,
            name,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<_i2.Workspace> create(
    _i3.Session? session,
    _i2.Workspace? workspace,
    int? ownerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            session,
            workspace,
            ownerId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #create,
            [
              session,
              workspace,
              ownerId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.WorkspaceMember?> findMemberByWorkspaceId(
    _i3.Session? session,
    int? userId,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMemberByWorkspaceId,
          [
            session,
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceMember?>.value(),
      ) as _i6.Future<_i2.WorkspaceMember?>);

  @override
  _i6.Future<_i2.Workspace?> findWorkspaceById(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWorkspaceById,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<bool> doesChildWorkspaceExist(
    _i3.Session? session,
    String? name,
    int? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doesChildWorkspaceExist,
          [
            session,
            name,
            parentId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> archiveWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> restoreWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> softDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hardDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> updateMemberRole(
    _i3.Session? session,
    int? memberId,
    _i2.WorkspaceRole? role,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [
            session,
            memberId,
            role,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deactivateMember(
    _i3.Session? session,
    int? memberId,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateMember,
          [
            session,
            memberId,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.WorkspaceInvitation> createInvitation(
    _i3.Session? session,
    _i2.WorkspaceInvitation? invitation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvitation,
          [
            session,
            invitation,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation>.value(
            _FakeWorkspaceInvitation_1(
          this,
          Invocation.method(
            #createInvitation,
            [
              session,
              invitation,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceInvitation>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> findInvitationByToken(
    _i3.Session? session,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInvitationByToken,
          [
            session,
            token,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);

  @override
  _i6.Future<void> deleteInvitation(
    _i3.Session? session,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInvitation,
          [
            session,
            token,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.WorkspaceMember?> findMemberByEmail(
    _i3.Session? session,
    String? email,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMemberByEmail,
          [
            session,
            email,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceMember?>.value(),
      ) as _i6.Future<_i2.WorkspaceMember?>);

  @override
  _i6.Future<_i2.WorkspaceMember> acceptInvitation(
    _i3.Session? session,
    _i2.WorkspaceInvitation? invitation,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [
            session,
            invitation,
            userId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_2(
          this,
          Invocation.method(
            #acceptInvitation,
            [
              session,
              invitation,
              userId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i3.Session {
  MockSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UuidValue get sessionId => (super.noSuchMethod(
        Invocation.getter(#sessionId),
        returnValue: _FakeUuidValue_3(
          this,
          Invocation.getter(#sessionId),
        ),
      ) as _i3.UuidValue);

  @override
  _i3.Server get server => (super.noSuchMethod(
        Invocation.getter(#server),
        returnValue: _FakeServer_4(
          this,
          Invocation.getter(#server),
        ),
      ) as _i3.Server);

  @override
  _i3.Serverpod get serverpod => (super.noSuchMethod(
        Invocation.getter(#serverpod),
        returnValue: _FakeServerpod_5(
          this,
          Invocation.getter(#serverpod),
        ),
      ) as _i3.Serverpod);

  @override
  DateTime get startTime => (super.noSuchMethod(
        Invocation.getter(#startTime),
        returnValue: _FakeDateTime_6(
          this,
          Invocation.getter(#startTime),
        ),
      ) as DateTime);

  @override
  _i6.Future<_i3.AuthenticationInfo?> get authenticated => (super.noSuchMethod(
        Invocation.getter(#authenticated),
        returnValue: _i6.Future<_i3.AuthenticationInfo?>.value(),
      ) as _i6.Future<_i3.AuthenticationInfo?>);

  @override
  _i6.Future<bool> get isUserSignedIn => (super.noSuchMethod(
        Invocation.getter(#isUserSignedIn),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i3.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_7(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.Database);

  @override
  _i4.Caches get caches => (super.noSuchMethod(
        Invocation.getter(#caches),
        returnValue: _FakeCaches_8(
          this,
          Invocation.getter(#caches),
        ),
      ) as _i4.Caches);

  @override
  Map<String, String> get passwords => (super.noSuchMethod(
        Invocation.getter(#passwords),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.StorageAccess get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageAccess_9(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.StorageAccess);

  @override
  _i3.MessageCentralAccess get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _FakeMessageCentralAccess_10(
          this,
          Invocation.getter(#messages),
        ),
      ) as _i3.MessageCentralAccess);

  @override
  bool get enableLogging => (super.noSuchMethod(
        Invocation.getter(#enableLogging),
        returnValue: false,
      ) as bool);

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
      ) as String);

  @override
  Duration get duration => (super.noSuchMethod(
        Invocation.getter(#duration),
        returnValue: _FakeDuration_11(
          this,
          Invocation.getter(#duration),
        ),
      ) as Duration);

  @override
  set userObject(dynamic value) => super.noSuchMethod(
        Invocation.setter(
          #userObject,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i3.StorageAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set messages(_i3.MessageCentralAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #messages,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addWillCloseListener(_i3.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeWillCloseListener(_i3.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAuthenticated(_i3.AuthenticationInfo? info) => super.noSuchMethod(
        Invocation.method(
          #updateAuthenticated,
          [info],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<int?> close({
    dynamic error,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  void log(
    String? message, {
    _i3.LogLevel? level,
    dynamic exception,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #exception: exception,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}
