// Mocks generated by Mockito 5.4.6 from annotations
// in hololine_server/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hololine_server/src/generated/protocol.dart' as _i2;
import 'package:hololine_server/src/modules/catalog/repositories/catalog_repo.dart'
    as _i14;
import 'package:hololine_server/src/modules/catalog/repositories/inventory_repo.dart'
    as _i15;
import 'package:hololine_server/src/modules/catalog/usecase/catalog_service.dart'
    as _i9;
import 'package:hololine_server/src/modules/inventory/usecase/inventory_service.dart'
    as _i10;
import 'package:hololine_server/src/modules/ledger/repositories/ledger_repo.dart'
    as _i16;
import 'package:hololine_server/src/modules/ledger/usecase/ledger_service.dart'
    as _i11;
import 'package:hololine_server/src/modules/workspace/repositories/repositories.dart'
    as _i12;
import 'package:hololine_server/src/modules/workspace/usecase/core_workspace_service.dart'
    as _i5;
import 'package:hololine_server/src/modules/workspace/usecase/invitation_service.dart'
    as _i8;
import 'package:hololine_server/src/modules/workspace/usecase/member_service.dart'
    as _i7;
import 'package:hololine_server/src/services/email_service.dart' as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:serverpod/serverpod.dart' as _i3;
import 'package:serverpod/src/cache/caches.dart' as _i4;
import 'package:serverpod_auth_server/serverpod_auth_server.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkspace_0 extends _i1.SmartFake implements _i2.Workspace {
  _FakeWorkspace_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkspaceMember_1 extends _i1.SmartFake
    implements _i2.WorkspaceMember {
  _FakeWorkspaceMember_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkspaceInvitation_2 extends _i1.SmartFake
    implements _i2.WorkspaceInvitation {
  _FakeWorkspaceInvitation_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCatalogSnapshot_3 extends _i1.SmartFake
    implements _i2.CatalogSnapshot {
  _FakeCatalogSnapshot_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCatalog_4 extends _i1.SmartFake implements _i2.Catalog {
  _FakeCatalog_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLedger_5 extends _i1.SmartFake implements _i2.Ledger {
  _FakeLedger_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventory_6 extends _i1.SmartFake implements _i2.Inventory {
  _FakeInventory_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuidValue_7 extends _i1.SmartFake implements _i3.UuidValue {
  _FakeUuidValue_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServer_8 extends _i1.SmartFake implements _i3.Server {
  _FakeServer_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerpod_9 extends _i1.SmartFake implements _i3.Serverpod {
  _FakeServerpod_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_10 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_11 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCaches_12 extends _i1.SmartFake implements _i4.Caches {
  _FakeCaches_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageAccess_13 extends _i1.SmartFake implements _i3.StorageAccess {
  _FakeStorageAccess_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageCentralAccess_14 extends _i1.SmartFake
    implements _i3.MessageCentralAccess {
  _FakeMessageCentralAccess_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_15 extends _i1.SmartFake implements Duration {
  _FakeDuration_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_16 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceService extends _i1.Mock implements _i5.WorkspaceService {
  MockWorkspaceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Workspace> createStandalone(
    _i3.Session? session,
    String? name,
    int? userId,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStandalone,
          [
            session,
            name,
            userId,
            description,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #createStandalone,
            [
              session,
              name,
              userId,
              description,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> createChild(
    _i3.Session? session,
    String? name,
    int? userId,
    int? parentWorkspaceId,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChild,
          [
            session,
            name,
            userId,
            parentWorkspaceId,
            description,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #createChild,
            [
              session,
              name,
              userId,
              parentWorkspaceId,
              description,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> getWorkspaceDetails(
    _i3.Session? session,
    String? publicId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceDetails,
          [
            session,
            publicId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #getWorkspaceDetails,
            [
              session,
              publicId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<List<_i2.Workspace>> getChildWorkspaces(
    _i3.Session? session,
    int? parentWorkspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildWorkspaces,
          [
            session,
            parentWorkspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Workspace>>.value(<_i2.Workspace>[]),
      ) as _i6.Future<List<_i2.Workspace>>);

  @override
  _i6.Future<_i2.Workspace> updateWorkspaceDetails(
    _i3.Session? session,
    int? workspaceId,
    String? name,
    String? description,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkspaceDetails,
          [
            session,
            workspaceId,
            name,
            description,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #updateWorkspaceDetails,
            [
              session,
              workspaceId,
              name,
              description,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> archiveWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #archiveWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> restoreWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #restoreWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<bool> transferOwnership(
    _i3.Session? session,
    int? workspaceId,
    int? newOwnerId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferOwnership,
          [
            session,
            workspaceId,
            newOwnerId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.Workspace> initiateDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateDeleteWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #initiateDeleteWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);
}

/// A class which mocks [MemberService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberService extends _i1.Mock implements _i7.MemberService {
  MockMemberService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.WorkspaceSummary>> getMyWorkspaces(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyWorkspaces,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.WorkspaceSummary>>.value(
            <_i2.WorkspaceSummary>[]),
      ) as _i6.Future<List<_i2.WorkspaceSummary>>);

  @override
  _i6.Future<_i2.WorkspaceMember> updateMemberRole(
    _i3.Session? session, {
    required int? memberId,
    required int? workspaceId,
    required _i2.WorkspaceRole? role,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [session],
          {
            #memberId: memberId,
            #workspaceId: workspaceId,
            #role: role,
            #actorId: actorId,
          },
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #updateMemberRole,
            [session],
            {
              #memberId: memberId,
              #workspaceId: workspaceId,
              #role: role,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<_i2.WorkspaceMember> removeMember(
    _i3.Session? session, {
    required int? memberId,
    required int? workspaceId,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [session],
          {
            #memberId: memberId,
            #workspaceId: workspaceId,
            #actorId: actorId,
          },
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #removeMember,
            [session],
            {
              #memberId: memberId,
              #workspaceId: workspaceId,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<_i2.WorkspaceMember> leaveWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #leaveWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);
}

/// A class which mocks [InvitationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationService extends _i1.Mock implements _i8.InvitationService {
  MockInvitationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WorkspaceInvitation> inviteMember(
    _i3.Session? session,
    String? email,
    int? workspaceId,
    _i2.WorkspaceRole? role,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteMember,
          [
            session,
            email,
            workspaceId,
            role,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation>.value(
            _FakeWorkspaceInvitation_2(
          this,
          Invocation.method(
            #inviteMember,
            [
              session,
              email,
              workspaceId,
              role,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceInvitation>);

  @override
  _i6.Future<_i2.WorkspaceMember> acceptInvitation(
    _i3.Session? session,
    String? token, {
    int? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [
            session,
            token,
          ],
          {#userId: userId},
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #acceptInvitation,
            [
              session,
              token,
            ],
            {#userId: userId},
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);
}

/// A class which mocks [CatalogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogService extends _i1.Mock implements _i9.CatalogService {
  MockCatalogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.CatalogSnapshot> getCatalogSnapshot(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCatalogSnapshot,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.CatalogSnapshot>.value(_FakeCatalogSnapshot_3(
          this,
          Invocation.method(
            #getCatalogSnapshot,
            [
              session,
              workspaceId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.CatalogSnapshot>);

  @override
  _i6.Future<_i2.Catalog> createProduct(
    _i3.Session? session, {
    required int? workspaceId,
    required _i2.Catalog? catalogData,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [session],
          {
            #workspaceId: workspaceId,
            #catalogData: catalogData,
            #actorId: actorId,
          },
        ),
        returnValue: _i6.Future<_i2.Catalog>.value(_FakeCatalog_4(
          this,
          Invocation.method(
            #createProduct,
            [session],
            {
              #workspaceId: workspaceId,
              #catalogData: catalogData,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Catalog>);

  @override
  _i6.Future<List<_i2.Catalog>> listProducts(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listProducts,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Catalog>>.value(<_i2.Catalog>[]),
      ) as _i6.Future<List<_i2.Catalog>>);

  @override
  _i6.Future<_i2.Catalog> updateProduct(
    _i3.Session? session, {
    required int? workspaceId,
    required int? catalogId,
    required _i2.CatalogUpdateParams? catalogUpdates,
    required _i2.InventoryUpdateParams? inventoryUpdates,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [session],
          {
            #workspaceId: workspaceId,
            #catalogId: catalogId,
            #catalogUpdates: catalogUpdates,
            #inventoryUpdates: inventoryUpdates,
            #actorId: actorId,
          },
        ),
        returnValue: _i6.Future<_i2.Catalog>.value(_FakeCatalog_4(
          this,
          Invocation.method(
            #updateProduct,
            [session],
            {
              #workspaceId: workspaceId,
              #catalogId: catalogId,
              #catalogUpdates: catalogUpdates,
              #inventoryUpdates: inventoryUpdates,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Catalog>);

  @override
  _i6.Future<void> archiveProduct(
    _i3.Session? session,
    int? workspaceId,
    int? catalogId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveProduct,
          [
            session,
            workspaceId,
            catalogId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [InventoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryService extends _i1.Mock implements _i10.InventoryService {
  MockInventoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Inventory>> listInventory(
    _i3.Session? session, {
    required int? workspaceId,
    required int? actorId,
    bool? includeDiscontinued = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listInventory,
          [session],
          {
            #workspaceId: workspaceId,
            #actorId: actorId,
            #includeDiscontinued: includeDiscontinued,
          },
        ),
        returnValue: _i6.Future<List<_i2.Inventory>>.value(<_i2.Inventory>[]),
      ) as _i6.Future<List<_i2.Inventory>>);

  @override
  _i6.Future<List<_i2.Inventory>> getLowStockItems(
    _i3.Session? session, {
    required int? workspaceId,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLowStockItems,
          [session],
          {
            #workspaceId: workspaceId,
            #actorId: actorId,
          },
        ),
        returnValue: _i6.Future<List<_i2.Inventory>>.value(<_i2.Inventory>[]),
      ) as _i6.Future<List<_i2.Inventory>>);

  @override
  _i6.Future<void> updateThreshold(
    _i3.Session? session, {
    required int? workspaceId,
    required int? catalogId,
    required double? threshold,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateThreshold,
          [session],
          {
            #workspaceId: workspaceId,
            #catalogId: catalogId,
            #threshold: threshold,
            #actorId: actorId,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [LedgerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLedgerService extends _i1.Mock implements _i11.LedgerService {
  MockLedgerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Ledger> createTransaction(
    _i3.Session? session, {
    required int? workspaceId,
    required int? actorId,
    required List<_i2.LedgerLineItem>? lineItems,
    required _i2.TransactionType? transactionType,
    required _i2.PaymentStatus? paymentStatus,
    required DateTime? transactionAt,
    String? referenceNumber,
    String? notes,
    String? counterpartyName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [session],
          {
            #workspaceId: workspaceId,
            #actorId: actorId,
            #lineItems: lineItems,
            #transactionType: transactionType,
            #paymentStatus: paymentStatus,
            #transactionAt: transactionAt,
            #referenceNumber: referenceNumber,
            #notes: notes,
            #counterpartyName: counterpartyName,
          },
        ),
        returnValue: _i6.Future<_i2.Ledger>.value(_FakeLedger_5(
          this,
          Invocation.method(
            #createTransaction,
            [session],
            {
              #workspaceId: workspaceId,
              #actorId: actorId,
              #lineItems: lineItems,
              #transactionType: transactionType,
              #paymentStatus: paymentStatus,
              #transactionAt: transactionAt,
              #referenceNumber: referenceNumber,
              #notes: notes,
              #counterpartyName: counterpartyName,
            },
          ),
        )),
      ) as _i6.Future<_i2.Ledger>);

  @override
  _i6.Future<List<_i2.Ledger>> listTransactions(
    _i3.Session? session, {
    required int? workspaceId,
    required int? actorId,
    _i2.TransactionType? transactionType,
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listTransactions,
          [session],
          {
            #workspaceId: workspaceId,
            #actorId: actorId,
            #transactionType: transactionType,
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i6.Future<List<_i2.Ledger>>.value(<_i2.Ledger>[]),
      ) as _i6.Future<List<_i2.Ledger>>);

  @override
  _i6.Future<_i2.Ledger> getTransaction(
    _i3.Session? session, {
    required int? ledgerId,
    required int? workspaceId,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [session],
          {
            #ledgerId: ledgerId,
            #workspaceId: workspaceId,
            #actorId: actorId,
          },
        ),
        returnValue: _i6.Future<_i2.Ledger>.value(_FakeLedger_5(
          this,
          Invocation.method(
            #getTransaction,
            [session],
            {
              #ledgerId: ledgerId,
              #workspaceId: workspaceId,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.Ledger>);
}

/// A class which mocks [WorkspaceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepo extends _i1.Mock implements _i12.WorkspaceRepo {
  MockWorkspaceRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i13.UserInfo?> getUserInfo(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i13.UserInfo?>.value(),
      ) as _i6.Future<_i13.UserInfo?>);

  @override
  _i6.Future<_i2.Workspace?> findByNameAndOwner(
    _i3.Session? session,
    String? name,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByNameAndOwner,
          [
            session,
            name,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<_i2.Workspace> create(
    _i3.Session? session,
    _i2.Workspace? workspace,
    int? ownerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            session,
            workspace,
            ownerId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #create,
            [
              session,
              workspace,
              ownerId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace?> findWorkspaceById(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWorkspaceById,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<_i2.Workspace?> findWorkspaceByPublicId(
    _i3.Session? session,
    String? publicId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWorkspaceByPublicId,
          [
            session,
            publicId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<List<_i2.Workspace>> findChildWorkspaces(
    _i3.Session? session,
    int? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findChildWorkspaces,
          [
            session,
            parentId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Workspace>>.value(<_i2.Workspace>[]),
      ) as _i6.Future<List<_i2.Workspace>>);

  @override
  _i6.Future<_i2.Workspace> update(
    _i3.Session? session,
    _i2.Workspace? workspace,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            session,
            workspace,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #update,
            [
              session,
              workspace,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<bool> doesChildWorkspaceExist(
    _i3.Session? session,
    String? name,
    int? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doesChildWorkspaceExist,
          [
            session,
            name,
            parentId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> archiveWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> restoreWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> softDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hardDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [MemberRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepo extends _i1.Mock implements _i12.MemberRepo {
  MockMemberRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WorkspaceMember?> findMemberByWorkspaceId(
    _i3.Session? session,
    int? userId,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMemberByWorkspaceId,
          [
            session,
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceMember?>.value(),
      ) as _i6.Future<_i2.WorkspaceMember?>);

  @override
  _i6.Future<List<_i2.WorkspaceSummary>> findUserWorkspaces(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserWorkspaces,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.WorkspaceSummary>>.value(
            <_i2.WorkspaceSummary>[]),
      ) as _i6.Future<List<_i2.WorkspaceSummary>>);

  @override
  _i6.Future<_i2.WorkspaceMember?> findMemberByEmail(
    _i3.Session? session,
    String? email,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMemberByEmail,
          [
            session,
            email,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceMember?>.value(),
      ) as _i6.Future<_i2.WorkspaceMember?>);

  @override
  _i6.Future<void> updateMemberRole(
    _i3.Session? session,
    int? memberId,
    _i2.WorkspaceRole? role,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [
            session,
            memberId,
            role,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> transferOwnership(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
    int? newOwnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferOwnership,
          [
            session,
            workspaceId,
            actorId,
            newOwnerId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.WorkspaceMember> deactivateMember(
    _i3.Session? session,
    int? memberId,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateMember,
          [
            session,
            memberId,
            workspaceId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #deactivateMember,
            [
              session,
              memberId,
              workspaceId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<List<_i2.WorkspaceMemberInfo>>
      findMembersWithUserInfoByWorkspaceId(
    _i3.Session? session,
    int? workspaceId,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #findMembersWithUserInfoByWorkspaceId,
              [
                session,
                workspaceId,
              ],
            ),
            returnValue: _i6.Future<List<_i2.WorkspaceMemberInfo>>.value(
                <_i2.WorkspaceMemberInfo>[]),
          ) as _i6.Future<List<_i2.WorkspaceMemberInfo>>);
}

/// A class which mocks [InvitationRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationRepo extends _i1.Mock implements _i12.InvitationRepo {
  MockInvitationRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WorkspaceInvitation> createInvitation(
    _i3.Session? session,
    _i2.WorkspaceInvitation? invitation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvitation,
          [
            session,
            invitation,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation>.value(
            _FakeWorkspaceInvitation_2(
          this,
          Invocation.method(
            #createInvitation,
            [
              session,
              invitation,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceInvitation>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> findInvitationByToken(
    _i3.Session? session,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInvitationByToken,
          [
            session,
            token,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);

  @override
  _i6.Future<void> deleteInvitation(
    _i3.Session? session,
    String? token, {
    _i3.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInvitation,
          [
            session,
            token,
          ],
          {#transaction: transaction},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.WorkspaceMember> acceptInvitation(
    _i3.Session? session,
    _i2.WorkspaceInvitation? invitation,
    int? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [
            session,
            invitation,
            userId,
            token,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #acceptInvitation,
            [
              session,
              invitation,
              userId,
              token,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> checkForExistingInvitation(
    _i3.Session? session,
    String? email,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForExistingInvitation,
          [
            session,
            email,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> checkIfTokenIsUnique(
    _i3.Session? session,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfTokenIsUnique,
          [
            session,
            token,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);
}

/// A class which mocks [CatalogRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatalogRepo extends _i1.Mock implements _i14.CatalogRepo {
  MockCatalogRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<int> countByWorkspaceId(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #countByWorkspaceId,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<_i2.Catalog?> findLastByWorkspaceId(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findLastByWorkspaceId,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.Catalog?>.value(),
      ) as _i6.Future<_i2.Catalog?>);

  @override
  _i6.Future<_i2.Catalog?> findById(
    _i3.Session? session,
    int? catalogId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [
            session,
            catalogId,
          ],
        ),
        returnValue: _i6.Future<_i2.Catalog?>.value(),
      ) as _i6.Future<_i2.Catalog?>);

  @override
  _i6.Future<bool> isSkuTaken(
    _i3.Session? session,
    String? sku,
    int? workspaceId, {
    int? excludeCatalogId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSkuTaken,
          [
            session,
            sku,
            workspaceId,
          ],
          {#excludeCatalogId: excludeCatalogId},
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i2.Catalog>> listProducts(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listProducts,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Catalog>>.value(<_i2.Catalog>[]),
      ) as _i6.Future<List<_i2.Catalog>>);

  @override
  _i6.Future<_i2.Catalog> insertWithTransaction(
    _i3.Session? session,
    _i2.Catalog? catalog,
    _i3.Transaction? transaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWithTransaction,
          [
            session,
            catalog,
            transaction,
          ],
        ),
        returnValue: _i6.Future<_i2.Catalog>.value(_FakeCatalog_4(
          this,
          Invocation.method(
            #insertWithTransaction,
            [
              session,
              catalog,
              transaction,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Catalog>);

  @override
  _i6.Future<_i2.Catalog> update(
    _i3.Session? session,
    _i2.Catalog? catalog, {
    _i3.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            session,
            catalog,
          ],
          {#transaction: transaction},
        ),
        returnValue: _i6.Future<_i2.Catalog>.value(_FakeCatalog_4(
          this,
          Invocation.method(
            #update,
            [
              session,
              catalog,
            ],
            {#transaction: transaction},
          ),
        )),
      ) as _i6.Future<_i2.Catalog>);

  @override
  _i6.Future<_i13.UserInfo?> getUserInfo(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i13.UserInfo?>.value(),
      ) as _i6.Future<_i13.UserInfo?>);

  @override
  _i6.Future<List<_i2.Catalog>> findByIds(
    _i3.Session? session,
    List<int>? catalogIds,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByIds,
          [
            session,
            catalogIds,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Catalog>>.value(<_i2.Catalog>[]),
      ) as _i6.Future<List<_i2.Catalog>>);
}

/// A class which mocks [InventoryRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryRepo extends _i1.Mock implements _i15.InventoryRepo {
  MockInventoryRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Inventory> insert(
    _i3.Session? session,
    _i2.Inventory? inventory, {
    _i3.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            session,
            inventory,
          ],
          {#transaction: transaction},
        ),
        returnValue: _i6.Future<_i2.Inventory>.value(_FakeInventory_6(
          this,
          Invocation.method(
            #insert,
            [
              session,
              inventory,
            ],
            {#transaction: transaction},
          ),
        )),
      ) as _i6.Future<_i2.Inventory>);

  @override
  _i6.Future<_i2.Inventory?> findByCatalogId(
    _i3.Session? session,
    int? catalogId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByCatalogId,
          [
            session,
            catalogId,
          ],
        ),
        returnValue: _i6.Future<_i2.Inventory?>.value(),
      ) as _i6.Future<_i2.Inventory?>);

  @override
  _i6.Future<_i2.Inventory> update(
    _i3.Session? session,
    _i2.Inventory? inventory, {
    _i3.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            session,
            inventory,
          ],
          {#transaction: transaction},
        ),
        returnValue: _i6.Future<_i2.Inventory>.value(_FakeInventory_6(
          this,
          Invocation.method(
            #update,
            [
              session,
              inventory,
            ],
            {#transaction: transaction},
          ),
        )),
      ) as _i6.Future<_i2.Inventory>);

  @override
  _i6.Future<List<_i2.Inventory>> listWithCatalog(
    _i3.Session? session,
    int? workspaceId, {
    bool? includeDiscontinued = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listWithCatalog,
          [
            session,
            workspaceId,
          ],
          {#includeDiscontinued: includeDiscontinued},
        ),
        returnValue: _i6.Future<List<_i2.Inventory>>.value(<_i2.Inventory>[]),
      ) as _i6.Future<List<_i2.Inventory>>);

  @override
  _i6.Future<List<_i2.Inventory>> getLowStockWithCatalog(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLowStockWithCatalog,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Inventory>>.value(<_i2.Inventory>[]),
      ) as _i6.Future<List<_i2.Inventory>>);

  @override
  _i6.Future<List<_i2.Inventory>> findByCatalogIds(
    _i3.Session? session,
    List<int>? catalogIds,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByCatalogIds,
          [
            session,
            catalogIds,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Inventory>>.value(<_i2.Inventory>[]),
      ) as _i6.Future<List<_i2.Inventory>>);

  @override
  _i6.Future<_i2.Inventory?> findByCatalogIdForUpdate(
    _i3.Session? session,
    int? catalogId,
    int? workspaceId,
    _i3.Transaction? transaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByCatalogIdForUpdate,
          [
            session,
            catalogId,
            workspaceId,
            transaction,
          ],
        ),
        returnValue: _i6.Future<_i2.Inventory?>.value(),
      ) as _i6.Future<_i2.Inventory?>);
}

/// A class which mocks [LedgerRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLedgerRepo extends _i1.Mock implements _i16.LedgerRepo {
  MockLedgerRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Ledger> insertWithTransaction(
    _i3.Session? session,
    _i2.Ledger? ledger,
    _i3.Transaction? transaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWithTransaction,
          [
            session,
            ledger,
            transaction,
          ],
        ),
        returnValue: _i6.Future<_i2.Ledger>.value(_FakeLedger_5(
          this,
          Invocation.method(
            #insertWithTransaction,
            [
              session,
              ledger,
              transaction,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Ledger>);

  @override
  _i6.Future<_i2.Ledger> updateWithTransaction(
    _i3.Session? session,
    _i2.Ledger? ledger,
    _i3.Transaction? transaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWithTransaction,
          [
            session,
            ledger,
            transaction,
          ],
        ),
        returnValue: _i6.Future<_i2.Ledger>.value(_FakeLedger_5(
          this,
          Invocation.method(
            #updateWithTransaction,
            [
              session,
              ledger,
              transaction,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Ledger>);

  @override
  _i6.Future<_i2.Ledger?> findById(
    _i3.Session? session,
    int? ledgerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findById,
          [
            session,
            ledgerId,
          ],
        ),
        returnValue: _i6.Future<_i2.Ledger?>.value(),
      ) as _i6.Future<_i2.Ledger?>);

  @override
  _i6.Future<_i2.Ledger?> findByIdWithLineItems(
    _i3.Session? session,
    int? ledgerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByIdWithLineItems,
          [
            session,
            ledgerId,
          ],
        ),
        returnValue: _i6.Future<_i2.Ledger?>.value(),
      ) as _i6.Future<_i2.Ledger?>);

  @override
  _i6.Future<List<_i2.Ledger>> list(
    _i3.Session? session,
    int? workspaceId, {
    _i2.TransactionType? transactionType,
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [
            session,
            workspaceId,
          ],
          {
            #transactionType: transactionType,
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i6.Future<List<_i2.Ledger>>.value(<_i2.Ledger>[]),
      ) as _i6.Future<List<_i2.Ledger>>);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i3.Session {
  MockSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UuidValue get sessionId => (super.noSuchMethod(
        Invocation.getter(#sessionId),
        returnValue: _FakeUuidValue_7(
          this,
          Invocation.getter(#sessionId),
        ),
      ) as _i3.UuidValue);

  @override
  _i3.Server get server => (super.noSuchMethod(
        Invocation.getter(#server),
        returnValue: _FakeServer_8(
          this,
          Invocation.getter(#server),
        ),
      ) as _i3.Server);

  @override
  _i3.Serverpod get serverpod => (super.noSuchMethod(
        Invocation.getter(#serverpod),
        returnValue: _FakeServerpod_9(
          this,
          Invocation.getter(#serverpod),
        ),
      ) as _i3.Serverpod);

  @override
  DateTime get startTime => (super.noSuchMethod(
        Invocation.getter(#startTime),
        returnValue: _FakeDateTime_10(
          this,
          Invocation.getter(#startTime),
        ),
      ) as DateTime);

  @override
  _i6.Future<_i3.AuthenticationInfo?> get authenticated => (super.noSuchMethod(
        Invocation.getter(#authenticated),
        returnValue: _i6.Future<_i3.AuthenticationInfo?>.value(),
      ) as _i6.Future<_i3.AuthenticationInfo?>);

  @override
  _i6.Future<bool> get isUserSignedIn => (super.noSuchMethod(
        Invocation.getter(#isUserSignedIn),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i3.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_11(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.Database);

  @override
  _i4.Caches get caches => (super.noSuchMethod(
        Invocation.getter(#caches),
        returnValue: _FakeCaches_12(
          this,
          Invocation.getter(#caches),
        ),
      ) as _i4.Caches);

  @override
  Map<String, String> get passwords => (super.noSuchMethod(
        Invocation.getter(#passwords),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.StorageAccess get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageAccess_13(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.StorageAccess);

  @override
  _i3.MessageCentralAccess get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _FakeMessageCentralAccess_14(
          this,
          Invocation.getter(#messages),
        ),
      ) as _i3.MessageCentralAccess);

  @override
  bool get enableLogging => (super.noSuchMethod(
        Invocation.getter(#enableLogging),
        returnValue: false,
      ) as bool);

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
      ) as String);

  @override
  Duration get duration => (super.noSuchMethod(
        Invocation.getter(#duration),
        returnValue: _FakeDuration_15(
          this,
          Invocation.getter(#duration),
        ),
      ) as Duration);

  @override
  set userObject(dynamic value) => super.noSuchMethod(
        Invocation.setter(
          #userObject,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i3.StorageAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set messages(_i3.MessageCentralAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #messages,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addWillCloseListener(_i3.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeWillCloseListener(_i3.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAuthenticated(_i3.AuthenticationInfo? info) => super.noSuchMethod(
        Invocation.method(
          #updateAuthenticated,
          [info],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<int?> close({
    dynamic error,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  void log(
    String? message, {
    _i3.LogLevel? level,
    dynamic exception,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #exception: exception,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EmailHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailHandler extends _i1.Mock implements _i18.EmailHandler {
  MockEmailHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Session get session => (super.noSuchMethod(
        Invocation.getter(#session),
        returnValue: _FakeSession_16(
          this,
          Invocation.getter(#session),
        ),
      ) as _i3.Session);

  @override
  _i6.Future<bool> sendVerificationEmail({
    required String? email,
    required String? verificationCode,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationEmail,
          [],
          {
            #email: email,
            #verificationCode: verificationCode,
            #userName: userName,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> sendPasswordResetEmail({
    required String? email,
    required String? resetCode,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {
            #email: email,
            #resetCode: resetCode,
            #userName: userName,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> sendInvitation(
    String? email,
    String? token,
    String? workspaceName,
    _i2.WorkspaceRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendInvitation,
          [
            email,
            token,
            workspaceName,
            role,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
