// Mocks generated by Mockito 5.4.6 from annotations
// in hololine_server/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:hololine_server/src/generated/protocol.dart' as _i2;
import 'package:hololine_server/src/modules/workspace/repositories/repositories.dart'
    as _i9;
import 'package:hololine_server/src/modules/workspace/usecase/core_workspace_service.dart'
    as _i5;
import 'package:hololine_server/src/modules/workspace/usecase/invitation_service.dart'
    as _i8;
import 'package:hololine_server/src/modules/workspace/usecase/member_service.dart'
    as _i7;
import 'package:hololine_server/src/services/email_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:serverpod/serverpod.dart' as _i3;
import 'package:serverpod/src/cache/caches.dart' as _i4;
import 'package:serverpod_auth_server/serverpod_auth_server.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkspace_0 extends _i1.SmartFake implements _i2.Workspace {
  _FakeWorkspace_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkspaceMember_1 extends _i1.SmartFake
    implements _i2.WorkspaceMember {
  _FakeWorkspaceMember_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkspaceInvitation_2 extends _i1.SmartFake
    implements _i2.WorkspaceInvitation {
  _FakeWorkspaceInvitation_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuidValue_3 extends _i1.SmartFake implements _i3.UuidValue {
  _FakeUuidValue_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServer_4 extends _i1.SmartFake implements _i3.Server {
  _FakeServer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerpod_5 extends _i1.SmartFake implements _i3.Serverpod {
  _FakeServerpod_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_6 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_7 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCaches_8 extends _i1.SmartFake implements _i4.Caches {
  _FakeCaches_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageAccess_9 extends _i1.SmartFake implements _i3.StorageAccess {
  _FakeStorageAccess_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageCentralAccess_10 extends _i1.SmartFake
    implements _i3.MessageCentralAccess {
  _FakeMessageCentralAccess_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_11 extends _i1.SmartFake implements Duration {
  _FakeDuration_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_12 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceService extends _i1.Mock implements _i5.WorkspaceService {
  MockWorkspaceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Workspace> createStandalone(
    _i3.Session? session,
    String? name,
    int? userId,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStandalone,
          [
            session,
            name,
            userId,
            description,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #createStandalone,
            [
              session,
              name,
              userId,
              description,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> createChild(
    _i3.Session? session,
    String? name,
    int? userId,
    int? parentWorkspaceId,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChild,
          [
            session,
            name,
            userId,
            parentWorkspaceId,
            description,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #createChild,
            [
              session,
              name,
              userId,
              parentWorkspaceId,
              description,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> getWorkspaceDetails(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceDetails,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #getWorkspaceDetails,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<List<_i2.Workspace>> getChildWorkspaces(
    _i3.Session? session,
    int? parentWorkspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildWorkspaces,
          [
            session,
            parentWorkspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Workspace>>.value(<_i2.Workspace>[]),
      ) as _i6.Future<List<_i2.Workspace>>);

  @override
  _i6.Future<_i2.Workspace> updateWorkspaceDetails(
    _i3.Session? session,
    int? workspaceId,
    String? name,
    String? description,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkspaceDetails,
          [
            session,
            workspaceId,
            name,
            description,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #updateWorkspaceDetails,
            [
              session,
              workspaceId,
              name,
              description,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> archiveWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #archiveWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace> restoreWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #restoreWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<bool> transferOwnership(
    _i3.Session? session,
    int? workspaceId,
    int? newOwnerId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferOwnership,
          [
            session,
            workspaceId,
            newOwnerId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.Workspace> initiateDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateDeleteWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #initiateDeleteWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);
}

/// A class which mocks [MemberService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberService extends _i1.Mock implements _i7.MemberService {
  MockMemberService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Workspace>> getMyWorkspaces(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyWorkspaces,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Workspace>>.value(<_i2.Workspace>[]),
      ) as _i6.Future<List<_i2.Workspace>>);

  @override
  _i6.Future<_i2.WorkspaceMember> updateMemberRole(
    _i3.Session? session, {
    required int? memberId,
    required int? workspaceId,
    required _i2.WorkspaceRole? role,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [session],
          {
            #memberId: memberId,
            #workspaceId: workspaceId,
            #role: role,
            #actorId: actorId,
          },
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #updateMemberRole,
            [session],
            {
              #memberId: memberId,
              #workspaceId: workspaceId,
              #role: role,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<_i2.WorkspaceMember> removeMember(
    _i3.Session? session, {
    required int? memberId,
    required int? workspaceId,
    required int? actorId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [session],
          {
            #memberId: memberId,
            #workspaceId: workspaceId,
            #actorId: actorId,
          },
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #removeMember,
            [session],
            {
              #memberId: memberId,
              #workspaceId: workspaceId,
              #actorId: actorId,
            },
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<_i2.WorkspaceMember> leaveWorkspace(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveWorkspace,
          [
            session,
            workspaceId,
            actorId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #leaveWorkspace,
            [
              session,
              workspaceId,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);
}

/// A class which mocks [InvitationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationService extends _i1.Mock implements _i8.InvitationService {
  MockInvitationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WorkspaceInvitation> inviteMember(
    _i3.Session? session,
    String? email,
    int? workspaceId,
    _i2.WorkspaceRole? role,
    int? actorId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteMember,
          [
            session,
            email,
            workspaceId,
            role,
            actorId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation>.value(
            _FakeWorkspaceInvitation_2(
          this,
          Invocation.method(
            #inviteMember,
            [
              session,
              email,
              workspaceId,
              role,
              actorId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceInvitation>);

  @override
  _i6.Future<_i2.WorkspaceMember> acceptInvitation(
    _i3.Session? session,
    String? token, {
    int? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [
            session,
            token,
          ],
          {#userId: userId},
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #acceptInvitation,
            [
              session,
              token,
            ],
            {#userId: userId},
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);
}

/// A class which mocks [WorkspaceRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepo extends _i1.Mock implements _i9.WorkspaceRepo {
  MockWorkspaceRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i10.UserInfo?> getUserInfo(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i10.UserInfo?>.value(),
      ) as _i6.Future<_i10.UserInfo?>);

  @override
  _i6.Future<_i2.Workspace?> findByNameAndOwner(
    _i3.Session? session,
    String? name,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByNameAndOwner,
          [
            session,
            name,
            userId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<_i2.Workspace> create(
    _i3.Session? session,
    _i2.Workspace? workspace,
    int? ownerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            session,
            workspace,
            ownerId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #create,
            [
              session,
              workspace,
              ownerId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<_i2.Workspace?> findWorkspaceById(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWorkspaceById,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace?>.value(),
      ) as _i6.Future<_i2.Workspace?>);

  @override
  _i6.Future<List<_i2.Workspace>> findChildWorkspaces(
    _i3.Session? session,
    int? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findChildWorkspaces,
          [
            session,
            parentId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Workspace>>.value(<_i2.Workspace>[]),
      ) as _i6.Future<List<_i2.Workspace>>);

  @override
  _i6.Future<_i2.Workspace> update(
    _i3.Session? session,
    _i2.Workspace? workspace,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            session,
            workspace,
          ],
        ),
        returnValue: _i6.Future<_i2.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #update,
            [
              session,
              workspace,
            ],
          ),
        )),
      ) as _i6.Future<_i2.Workspace>);

  @override
  _i6.Future<bool> doesChildWorkspaceExist(
    _i3.Session? session,
    String? name,
    int? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #doesChildWorkspaceExist,
          [
            session,
            name,
            parentId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> archiveWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> restoreWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> softDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hardDeleteWorkspace(
    _i3.Session? session,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteWorkspace,
          [
            session,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [MemberRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepo extends _i1.Mock implements _i9.MemberRepo {
  MockMemberRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WorkspaceMember?> findMemberByWorkspaceId(
    _i3.Session? session,
    int? userId,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMemberByWorkspaceId,
          [
            session,
            userId,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceMember?>.value(),
      ) as _i6.Future<_i2.WorkspaceMember?>);

  @override
  _i6.Future<List<_i2.Workspace>> findUserWorkspaces(
    _i3.Session? session,
    int? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserWorkspaces,
          [
            session,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i2.Workspace>>.value(<_i2.Workspace>[]),
      ) as _i6.Future<List<_i2.Workspace>>);

  @override
  _i6.Future<_i2.WorkspaceMember?> findMemberByEmail(
    _i3.Session? session,
    String? email,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMemberByEmail,
          [
            session,
            email,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceMember?>.value(),
      ) as _i6.Future<_i2.WorkspaceMember?>);

  @override
  _i6.Future<void> updateMemberRole(
    _i3.Session? session,
    int? memberId,
    _i2.WorkspaceRole? role,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberRole,
          [
            session,
            memberId,
            role,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> transferOwnership(
    _i3.Session? session,
    int? workspaceId,
    int? actorId,
    int? newOwnerId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferOwnership,
          [
            session,
            workspaceId,
            actorId,
            newOwnerId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i2.WorkspaceMember> deactivateMember(
    _i3.Session? session,
    int? memberId,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deactivateMember,
          [
            session,
            memberId,
            workspaceId,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #deactivateMember,
            [
              session,
              memberId,
              workspaceId,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);
}

/// A class which mocks [InvitationRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvitationRepo extends _i1.Mock implements _i9.InvitationRepo {
  MockInvitationRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.WorkspaceInvitation> createInvitation(
    _i3.Session? session,
    _i2.WorkspaceInvitation? invitation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvitation,
          [
            session,
            invitation,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation>.value(
            _FakeWorkspaceInvitation_2(
          this,
          Invocation.method(
            #createInvitation,
            [
              session,
              invitation,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceInvitation>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> findInvitationByToken(
    _i3.Session? session,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findInvitationByToken,
          [
            session,
            token,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);

  @override
  _i6.Future<void> deleteInvitation(
    _i3.Session? session,
    String? token, {
    _i3.Transaction? transaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteInvitation,
          [
            session,
            token,
          ],
          {#transaction: transaction},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.WorkspaceMember> acceptInvitation(
    _i3.Session? session,
    _i2.WorkspaceInvitation? invitation,
    int? userId,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [
            session,
            invitation,
            userId,
            token,
          ],
        ),
        returnValue:
            _i6.Future<_i2.WorkspaceMember>.value(_FakeWorkspaceMember_1(
          this,
          Invocation.method(
            #acceptInvitation,
            [
              session,
              invitation,
              userId,
              token,
            ],
          ),
        )),
      ) as _i6.Future<_i2.WorkspaceMember>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> checkForExistingInvitation(
    _i3.Session? session,
    String? email,
    int? workspaceId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForExistingInvitation,
          [
            session,
            email,
            workspaceId,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);

  @override
  _i6.Future<_i2.WorkspaceInvitation?> checkIfTokenIsUnique(
    _i3.Session? session,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIfTokenIsUnique,
          [
            session,
            token,
          ],
        ),
        returnValue: _i6.Future<_i2.WorkspaceInvitation?>.value(),
      ) as _i6.Future<_i2.WorkspaceInvitation?>);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i3.Session {
  MockSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UuidValue get sessionId => (super.noSuchMethod(
        Invocation.getter(#sessionId),
        returnValue: _FakeUuidValue_3(
          this,
          Invocation.getter(#sessionId),
        ),
      ) as _i3.UuidValue);

  @override
  _i3.Server get server => (super.noSuchMethod(
        Invocation.getter(#server),
        returnValue: _FakeServer_4(
          this,
          Invocation.getter(#server),
        ),
      ) as _i3.Server);

  @override
  _i3.Serverpod get serverpod => (super.noSuchMethod(
        Invocation.getter(#serverpod),
        returnValue: _FakeServerpod_5(
          this,
          Invocation.getter(#serverpod),
        ),
      ) as _i3.Serverpod);

  @override
  DateTime get startTime => (super.noSuchMethod(
        Invocation.getter(#startTime),
        returnValue: _FakeDateTime_6(
          this,
          Invocation.getter(#startTime),
        ),
      ) as DateTime);

  @override
  _i6.Future<_i3.AuthenticationInfo?> get authenticated => (super.noSuchMethod(
        Invocation.getter(#authenticated),
        returnValue: _i6.Future<_i3.AuthenticationInfo?>.value(),
      ) as _i6.Future<_i3.AuthenticationInfo?>);

  @override
  _i6.Future<bool> get isUserSignedIn => (super.noSuchMethod(
        Invocation.getter(#isUserSignedIn),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i3.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_7(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.Database);

  @override
  _i4.Caches get caches => (super.noSuchMethod(
        Invocation.getter(#caches),
        returnValue: _FakeCaches_8(
          this,
          Invocation.getter(#caches),
        ),
      ) as _i4.Caches);

  @override
  Map<String, String> get passwords => (super.noSuchMethod(
        Invocation.getter(#passwords),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.StorageAccess get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorageAccess_9(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.StorageAccess);

  @override
  _i3.MessageCentralAccess get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _FakeMessageCentralAccess_10(
          this,
          Invocation.getter(#messages),
        ),
      ) as _i3.MessageCentralAccess);

  @override
  bool get enableLogging => (super.noSuchMethod(
        Invocation.getter(#enableLogging),
        returnValue: false,
      ) as bool);

  @override
  String get endpoint => (super.noSuchMethod(
        Invocation.getter(#endpoint),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#endpoint),
        ),
      ) as String);

  @override
  Duration get duration => (super.noSuchMethod(
        Invocation.getter(#duration),
        returnValue: _FakeDuration_11(
          this,
          Invocation.getter(#duration),
        ),
      ) as Duration);

  @override
  set userObject(dynamic value) => super.noSuchMethod(
        Invocation.setter(
          #userObject,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i3.StorageAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set messages(_i3.MessageCentralAccess? value) => super.noSuchMethod(
        Invocation.setter(
          #messages,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addWillCloseListener(_i3.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeWillCloseListener(_i3.WillCloseListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeWillCloseListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAuthenticated(_i3.AuthenticationInfo? info) => super.noSuchMethod(
        Invocation.method(
          #updateAuthenticated,
          [info],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<int?> close({
    dynamic error,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  void log(
    String? message, {
    _i3.LogLevel? level,
    dynamic exception,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #exception: exception,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EmailHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailHandler extends _i1.Mock implements _i12.EmailHandler {
  MockEmailHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Session get session => (super.noSuchMethod(
        Invocation.getter(#session),
        returnValue: _FakeSession_12(
          this,
          Invocation.getter(#session),
        ),
      ) as _i3.Session);

  @override
  _i6.Future<bool> sendVerificationEmail({
    required String? email,
    required String? verificationCode,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationEmail,
          [],
          {
            #email: email,
            #verificationCode: verificationCode,
            #userName: userName,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> sendPasswordResetEmail({
    required String? email,
    required String? resetCode,
    required String? userName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [],
          {
            #email: email,
            #resetCode: resetCode,
            #userName: userName,
          },
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> sendInvitation(
    String? email,
    String? token,
    String? workspaceName,
    _i2.WorkspaceRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendInvitation,
          [
            email,
            token,
            workspaceName,
            role,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
